include: package:lint/analysis_options.yaml

analyzer:
  errors:
    sized_box_for_whitespace: false
    argument_type_not_assignable: false
    avoid_print: false
    avoid_bool_literals_in_conditional_expressions: false
    constant_identifier_names: false
    file_names: false
    sort_pub_dependencies: false





#     avoid_redundant_argument_values: false
#     constant_identifier_names: false

  

#     # prefer_const_constructore: false



# #
# # linter:
# #   rules:
#     - prefer_const_constructors

# #///////////////////////////////

# #     avoid_unused_constructor_parameters: true
  #  avoid_classes_with_only_static_members: false


    






#     # # ------ Disable individual rules ----- #
#     # #                 ---                   #
#     # # Turn off what you don't like.         #
#     # # ------------------------------------- #

#     # # Use parameter order as in json response
#     # always_put_required_named_parameters_first: false
    
#     # # Util classes are awesome!
#     # avoid_classes_with_only_static_members: false


#     # # ------ Enable individual rules ------ #
#     # #                 ---                   #
#     # # These rules here are good but too     #
#     # # opinionated to enable them by default #
#     # # ------------------------------------- #

#     # # Make constructors the first thing in every class
#     # sort_constructors_first: true

#     # # The new tabs vs. spaces. Choose wisely
#     # prefer_single_quotes: true
#     # prefer_double_quotes: true

#     # # Good packages document everything
#     # public_member_api_docs: true
    
#     # # Blindly follow the Flutter code style, which prefers types everywhere
#     # always_specify_types: true
  
#     # # Back to the 80s
#     # lines_longer_than_80_chars: true